package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AntecedenteGeneral generated by hbm2java
 */
public class AntecedenteGeneral implements java.io.Serializable {

	private int antecedenteGralId;
	private HistoriaClinica historiaClinica;
	private String antecedentePesoalnacer;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String antecedenteTalla;
	private String antecedenteCcefalic;
	private String antecedentePartoNormal;
	private String antecedentePartoDistocico;
	private String antecedentePartoCesaria;
	private String antecedenteComplicaciones;
	private String antecedenteScoredeapgar;
	private String antecedenteSocioEconomico;
	private String antecedenteDiabetes;
	private String antecedenteAsma;
	private String antecedenteTbc;
	private String antecedenteHipertension;
	private String antecedentePadre;
	private String antecedenteMadre;
	private String antecedenteHijos;
	private String antecedenteHermanos;
	private String antecedenteTabaco;
	private String antecedenteAlcohol;
	private String antecedenteAdiccion;
	private Date antecedenteOperacionanterior;
	private String antecedenteTipooperacion;
	private Date antecedenteTraumatismos;
	private String antecedenteLocalizacion;
	private String antecedentePeso;
	private String antecedenteGeneralTalla;
	private String antecedenteTensionarterial;
	private String antecedentePielyfaneras;
	private String antecedenteVision;
	private String antecedenteAudicion;
	private String antecedenteOdontologia;
	private String antecedenteObesidad;
	private String antecedentePesonormal;
	private String antecedentePesobajo;
	private String antecedenteReaccionAdversa;

	public AntecedenteGeneral() {
	}

	public AntecedenteGeneral(int antecedenteGralId) {
		this.antecedenteGralId = antecedenteGralId;
	}

	public AntecedenteGeneral(int antecedenteGralId,
			HistoriaClinica historiaClinica, String antecedentePesoalnacer,
			String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion,
			String antecedenteTalla, String antecedenteCcefalic,
			String antecedentePartoNormal, String antecedentePartoDistocico,
			String antecedentePartoCesaria, String antecedenteComplicaciones,
			String antecedenteScoredeapgar, String antecedenteSocioEconomico,
			String antecedenteDiabetes, String antecedenteAsma,
			String antecedenteTbc, String antecedenteHipertension,
			String antecedentePadre, String antecedenteMadre,
			String antecedenteHijos, String antecedenteHermanos,
			String antecedenteTabaco, String antecedenteAlcohol,
			String antecedenteAdiccion, Date antecedenteOperacionanterior,
			String antecedenteTipooperacion, Date antecedenteTraumatismos,
			String antecedenteLocalizacion, String antecedentePeso,
			String antecedenteGeneralTalla, String antecedenteTensionarterial,
			String antecedentePielyfaneras, String antecedenteVision,
			String antecedenteAudicion, String antecedenteOdontologia,
			String antecedenteObesidad, String antecedentePesonormal,
			String antecedentePesobajo, String antecedenteReaccionAdversa) {
		this.antecedenteGralId = antecedenteGralId;
		this.historiaClinica = historiaClinica;
		this.antecedentePesoalnacer = antecedentePesoalnacer;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.antecedenteTalla = antecedenteTalla;
		this.antecedenteCcefalic = antecedenteCcefalic;
		this.antecedentePartoNormal = antecedentePartoNormal;
		this.antecedentePartoDistocico = antecedentePartoDistocico;
		this.antecedentePartoCesaria = antecedentePartoCesaria;
		this.antecedenteComplicaciones = antecedenteComplicaciones;
		this.antecedenteScoredeapgar = antecedenteScoredeapgar;
		this.antecedenteSocioEconomico = antecedenteSocioEconomico;
		this.antecedenteDiabetes = antecedenteDiabetes;
		this.antecedenteAsma = antecedenteAsma;
		this.antecedenteTbc = antecedenteTbc;
		this.antecedenteHipertension = antecedenteHipertension;
		this.antecedentePadre = antecedentePadre;
		this.antecedenteMadre = antecedenteMadre;
		this.antecedenteHijos = antecedenteHijos;
		this.antecedenteHermanos = antecedenteHermanos;
		this.antecedenteTabaco = antecedenteTabaco;
		this.antecedenteAlcohol = antecedenteAlcohol;
		this.antecedenteAdiccion = antecedenteAdiccion;
		this.antecedenteOperacionanterior = antecedenteOperacionanterior;
		this.antecedenteTipooperacion = antecedenteTipooperacion;
		this.antecedenteTraumatismos = antecedenteTraumatismos;
		this.antecedenteLocalizacion = antecedenteLocalizacion;
		this.antecedentePeso = antecedentePeso;
		this.antecedenteGeneralTalla = antecedenteGeneralTalla;
		this.antecedenteTensionarterial = antecedenteTensionarterial;
		this.antecedentePielyfaneras = antecedentePielyfaneras;
		this.antecedenteVision = antecedenteVision;
		this.antecedenteAudicion = antecedenteAudicion;
		this.antecedenteOdontologia = antecedenteOdontologia;
		this.antecedenteObesidad = antecedenteObesidad;
		this.antecedentePesonormal = antecedentePesonormal;
		this.antecedentePesobajo = antecedentePesobajo;
		this.antecedenteReaccionAdversa = antecedenteReaccionAdversa;
	}

	public int getAntecedenteGralId() {
		return this.antecedenteGralId;
	}

	public void setAntecedenteGralId(int antecedenteGralId) {
		this.antecedenteGralId = antecedenteGralId;
	}

	public HistoriaClinica getHistoriaClinica() {
		return this.historiaClinica;
	}

	public void setHistoriaClinica(HistoriaClinica historiaClinica) {
		this.historiaClinica = historiaClinica;
	}

	public String getAntecedentePesoalnacer() {
		return this.antecedentePesoalnacer;
	}

	public void setAntecedentePesoalnacer(String antecedentePesoalnacer) {
		this.antecedentePesoalnacer = antecedentePesoalnacer;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getAntecedenteTalla() {
		return this.antecedenteTalla;
	}

	public void setAntecedenteTalla(String antecedenteTalla) {
		this.antecedenteTalla = antecedenteTalla;
	}

	public String getAntecedenteCcefalic() {
		return this.antecedenteCcefalic;
	}

	public void setAntecedenteCcefalic(String antecedenteCcefalic) {
		this.antecedenteCcefalic = antecedenteCcefalic;
	}

	public String getAntecedentePartoNormal() {
		return this.antecedentePartoNormal;
	}

	public void setAntecedentePartoNormal(String antecedentePartoNormal) {
		this.antecedentePartoNormal = antecedentePartoNormal;
	}

	public String getAntecedentePartoDistocico() {
		return this.antecedentePartoDistocico;
	}

	public void setAntecedentePartoDistocico(String antecedentePartoDistocico) {
		this.antecedentePartoDistocico = antecedentePartoDistocico;
	}

	public String getAntecedentePartoCesaria() {
		return this.antecedentePartoCesaria;
	}

	public void setAntecedentePartoCesaria(String antecedentePartoCesaria) {
		this.antecedentePartoCesaria = antecedentePartoCesaria;
	}

	public String getAntecedenteComplicaciones() {
		return this.antecedenteComplicaciones;
	}

	public void setAntecedenteComplicaciones(String antecedenteComplicaciones) {
		this.antecedenteComplicaciones = antecedenteComplicaciones;
	}

	public String getAntecedenteScoredeapgar() {
		return this.antecedenteScoredeapgar;
	}

	public void setAntecedenteScoredeapgar(String antecedenteScoredeapgar) {
		this.antecedenteScoredeapgar = antecedenteScoredeapgar;
	}

	public String getAntecedenteSocioEconomico() {
		return this.antecedenteSocioEconomico;
	}

	public void setAntecedenteSocioEconomico(String antecedenteSocioEconomico) {
		this.antecedenteSocioEconomico = antecedenteSocioEconomico;
	}

	public String getAntecedenteDiabetes() {
		return this.antecedenteDiabetes;
	}

	public void setAntecedenteDiabetes(String antecedenteDiabetes) {
		this.antecedenteDiabetes = antecedenteDiabetes;
	}

	public String getAntecedenteAsma() {
		return this.antecedenteAsma;
	}

	public void setAntecedenteAsma(String antecedenteAsma) {
		this.antecedenteAsma = antecedenteAsma;
	}

	public String getAntecedenteTbc() {
		return this.antecedenteTbc;
	}

	public void setAntecedenteTbc(String antecedenteTbc) {
		this.antecedenteTbc = antecedenteTbc;
	}

	public String getAntecedenteHipertension() {
		return this.antecedenteHipertension;
	}

	public void setAntecedenteHipertension(String antecedenteHipertension) {
		this.antecedenteHipertension = antecedenteHipertension;
	}

	public String getAntecedentePadre() {
		return this.antecedentePadre;
	}

	public void setAntecedentePadre(String antecedentePadre) {
		this.antecedentePadre = antecedentePadre;
	}

	public String getAntecedenteMadre() {
		return this.antecedenteMadre;
	}

	public void setAntecedenteMadre(String antecedenteMadre) {
		this.antecedenteMadre = antecedenteMadre;
	}

	public String getAntecedenteHijos() {
		return this.antecedenteHijos;
	}

	public void setAntecedenteHijos(String antecedenteHijos) {
		this.antecedenteHijos = antecedenteHijos;
	}

	public String getAntecedenteHermanos() {
		return this.antecedenteHermanos;
	}

	public void setAntecedenteHermanos(String antecedenteHermanos) {
		this.antecedenteHermanos = antecedenteHermanos;
	}

	public String getAntecedenteTabaco() {
		return this.antecedenteTabaco;
	}

	public void setAntecedenteTabaco(String antecedenteTabaco) {
		this.antecedenteTabaco = antecedenteTabaco;
	}

	public String getAntecedenteAlcohol() {
		return this.antecedenteAlcohol;
	}

	public void setAntecedenteAlcohol(String antecedenteAlcohol) {
		this.antecedenteAlcohol = antecedenteAlcohol;
	}

	public String getAntecedenteAdiccion() {
		return this.antecedenteAdiccion;
	}

	public void setAntecedenteAdiccion(String antecedenteAdiccion) {
		this.antecedenteAdiccion = antecedenteAdiccion;
	}

	public Date getAntecedenteOperacionanterior() {
		return this.antecedenteOperacionanterior;
	}

	public void setAntecedenteOperacionanterior(
			Date antecedenteOperacionanterior) {
		this.antecedenteOperacionanterior = antecedenteOperacionanterior;
	}

	public String getAntecedenteTipooperacion() {
		return this.antecedenteTipooperacion;
	}

	public void setAntecedenteTipooperacion(String antecedenteTipooperacion) {
		this.antecedenteTipooperacion = antecedenteTipooperacion;
	}

	public Date getAntecedenteTraumatismos() {
		return this.antecedenteTraumatismos;
	}

	public void setAntecedenteTraumatismos(Date antecedenteTraumatismos) {
		this.antecedenteTraumatismos = antecedenteTraumatismos;
	}

	public String getAntecedenteLocalizacion() {
		return this.antecedenteLocalizacion;
	}

	public void setAntecedenteLocalizacion(String antecedenteLocalizacion) {
		this.antecedenteLocalizacion = antecedenteLocalizacion;
	}

	public String getAntecedentePeso() {
		return this.antecedentePeso;
	}

	public void setAntecedentePeso(String antecedentePeso) {
		this.antecedentePeso = antecedentePeso;
	}

	public String getAntecedenteGeneralTalla() {
		return this.antecedenteGeneralTalla;
	}

	public void setAntecedenteGeneralTalla(String antecedenteGeneralTalla) {
		this.antecedenteGeneralTalla = antecedenteGeneralTalla;
	}

	public String getAntecedenteTensionarterial() {
		return this.antecedenteTensionarterial;
	}

	public void setAntecedenteTensionarterial(String antecedenteTensionarterial) {
		this.antecedenteTensionarterial = antecedenteTensionarterial;
	}

	public String getAntecedentePielyfaneras() {
		return this.antecedentePielyfaneras;
	}

	public void setAntecedentePielyfaneras(String antecedentePielyfaneras) {
		this.antecedentePielyfaneras = antecedentePielyfaneras;
	}

	public String getAntecedenteVision() {
		return this.antecedenteVision;
	}

	public void setAntecedenteVision(String antecedenteVision) {
		this.antecedenteVision = antecedenteVision;
	}

	public String getAntecedenteAudicion() {
		return this.antecedenteAudicion;
	}

	public void setAntecedenteAudicion(String antecedenteAudicion) {
		this.antecedenteAudicion = antecedenteAudicion;
	}

	public String getAntecedenteOdontologia() {
		return this.antecedenteOdontologia;
	}

	public void setAntecedenteOdontologia(String antecedenteOdontologia) {
		this.antecedenteOdontologia = antecedenteOdontologia;
	}

	public String getAntecedenteObesidad() {
		return this.antecedenteObesidad;
	}

	public void setAntecedenteObesidad(String antecedenteObesidad) {
		this.antecedenteObesidad = antecedenteObesidad;
	}

	public String getAntecedentePesonormal() {
		return this.antecedentePesonormal;
	}

	public void setAntecedentePesonormal(String antecedentePesonormal) {
		this.antecedentePesonormal = antecedentePesonormal;
	}

	public String getAntecedentePesobajo() {
		return this.antecedentePesobajo;
	}

	public void setAntecedentePesobajo(String antecedentePesobajo) {
		this.antecedentePesobajo = antecedentePesobajo;
	}

	public String getAntecedenteReaccionAdversa() {
		return this.antecedenteReaccionAdversa;
	}

	public void setAntecedenteReaccionAdversa(String antecedenteReaccionAdversa) {
		this.antecedenteReaccionAdversa = antecedenteReaccionAdversa;
	}

}
