package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento implements java.io.Serializable {

	private int medicamentoId;
	private String medicamentoNombre;
	private String medicamentoDescripcion;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Set tratamientoMedicamentos = new HashSet(0);

	public Medicamento() {
	}

	public Medicamento(int medicamentoId) {
		this.medicamentoId = medicamentoId;
	}



	public Medicamento(int medicamentoId, String medicamentoNombre,
			String medicamentoDescripcion, String usuarioCreacion,
			Date fechaCreacion, String usuarioModificacion,
			Date fechaModificacion) {
		super();
		this.medicamentoId = medicamentoId;
		this.medicamentoNombre = medicamentoNombre;
		this.medicamentoDescripcion = medicamentoDescripcion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
	}

	public Medicamento(String medicamentoNombre, String medicamentoDescripcion,
			String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion) {
		super();
		this.medicamentoNombre = medicamentoNombre;
		this.medicamentoDescripcion = medicamentoDescripcion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
	}

	public int getMedicamentoId() {
		return this.medicamentoId;
	}

	public void setMedicamentoId(int medicamentoId) {
		this.medicamentoId = medicamentoId;
	}

	public String getMedicamentoNombre() {
		return this.medicamentoNombre;
	}

	public void setMedicamentoNombre(String medicamentoNombre) {
		this.medicamentoNombre = medicamentoNombre;
	}

	public String getMedicamentoDescripcion() {
		return this.medicamentoDescripcion;
	}

	public void setMedicamentoDescripcion(String medicamentoDescripcion) {
		this.medicamentoDescripcion = medicamentoDescripcion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Set getTratamientoMedicamentos() {
		return this.tratamientoMedicamentos;
	}

	public void setTratamientoMedicamentos(Set tratamientoMedicamentos) {
		this.tratamientoMedicamentos = tratamientoMedicamentos;
	}

}
