package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Patologia generated by hbm2java
 */
public class Patologia implements java.io.Serializable {

	private int patologiaId;
	private String patologiaNombre;
	private String patologiaDescripcion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Set detallePatologias = new HashSet(0);

	public Patologia() {
	}

	public Patologia(int patologiaId) {
		this.patologiaId = patologiaId;
	}



	public Patologia(int patologiaId, String patologiaNombre,
			String patologiaDescripcion, Date fechaCreacion,
			Date fechaModificacion, String usuarioCreacion,
			String usuarioModificacion) {
		super();
		this.patologiaId = patologiaId;
		this.patologiaNombre = patologiaNombre;
		this.patologiaDescripcion = patologiaDescripcion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
	}

	public int getPatologiaId() {
		return this.patologiaId;
	}

	public void setPatologiaId(int patologiaId) {
		this.patologiaId = patologiaId;
	}

	public String getPatologiaNombre() {
		return this.patologiaNombre;
	}

	public void setPatologiaNombre(String patologiaNombre) {
		this.patologiaNombre = patologiaNombre;
	}

	public String getPatologiaDescripcion() {
		return this.patologiaDescripcion;
	}

	public void setPatologiaDescripcion(String patologiaDescripcion) {
		this.patologiaDescripcion = patologiaDescripcion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Set getDetallePatologias() {
		return this.detallePatologias;
	}

	public void setDetallePatologias(Set detallePatologias) {
		this.detallePatologias = detallePatologias;
	}

}
