package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento implements java.io.Serializable {

	private int tratamientoId;
	private Diagnostico diagnostico;
	private String tratamientoDescripcion;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Set tratamientoMedicamentos = new HashSet(0);

	public Tratamiento() {
	}

	public Tratamiento(int tratamientoId) {
		this.tratamientoId = tratamientoId;
	}



	public Tratamiento(int tratamientoId, Diagnostico diagnostico,
			String tratamientoDescripcion, String usuarioCreacion,
			Date fechaCreacion, String usuarioModificacion,
			Date fechaModificacion) {
		super();
		this.tratamientoId = tratamientoId;
		this.diagnostico = diagnostico;
		this.tratamientoDescripcion = tratamientoDescripcion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
	}

	public int getTratamientoId() {
		return this.tratamientoId;
	}

	public void setTratamientoId(int tratamientoId) {
		this.tratamientoId = tratamientoId;
	}

	public Diagnostico getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(Diagnostico diagnostico) {
		this.diagnostico = diagnostico;
	}

	public String getTratamientoDescripcion() {
		return this.tratamientoDescripcion;
	}

	public void setTratamientoDescripcion(String tratamientoDescripcion) {
		this.tratamientoDescripcion = tratamientoDescripcion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Set getTratamientoMedicamentos() {
		return this.tratamientoMedicamentos;
	}

	public void setTratamientoMedicamentos(Set tratamientoMedicamentos) {
		this.tratamientoMedicamentos = tratamientoMedicamentos;
	}

}
