package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TratamientoMedicamento generated by hbm2java
 */
public class TratamientoMedicamento implements java.io.Serializable {

	private int tratamientoMedicamentoId;
	private Tratamiento tratamiento;
	private Medicamento medicamento;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;

	public TratamientoMedicamento() {
	}

	public TratamientoMedicamento(int tratamientoMedicamentoId) {
		this.tratamientoMedicamentoId = tratamientoMedicamentoId;
	}

	public TratamientoMedicamento(int tratamientoMedicamentoId,
			Tratamiento tratamiento, Medicamento medicamento,
			String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion) {
		this.tratamientoMedicamentoId = tratamientoMedicamentoId;
		this.tratamiento = tratamiento;
		this.medicamento = medicamento;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
	}

	public int getTratamientoMedicamentoId() {
		return this.tratamientoMedicamentoId;
	}

	public void setTratamientoMedicamentoId(int tratamientoMedicamentoId) {
		this.tratamientoMedicamentoId = tratamientoMedicamentoId;
	}

	public Tratamiento getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(Tratamiento tratamiento) {
		this.tratamiento = tratamiento;
	}

	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
