package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Turno generated by hbm2java
 */
public class Turno implements java.io.Serializable {

	private int turnoId;
	private Paciente paciente;
	private Date turnoFecha;
	private Date turnoHora;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;

	public Turno() {
	}

	public Turno(int turnoId) {
		this.turnoId = turnoId;
	}

	public Turno(int turnoId, Paciente paciente, Date turnoFecha,
			Date turnoHora, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion) {
		this.turnoId = turnoId;
		this.paciente = paciente;
		this.turnoFecha = turnoFecha;
		this.turnoHora = turnoHora;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
	}

	public int getTurnoId() {
		return this.turnoId;
	}

	public void setTurnoId(int turnoId) {
		this.turnoId = turnoId;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public Date getTurnoFecha() {
		return this.turnoFecha;
	}

	public void setTurnoFecha(Date turnoFecha) {
		this.turnoFecha = turnoFecha;
	}

	public Date getTurnoHora() {
		return this.turnoHora;
	}

	public void setTurnoHora(Date turnoHora) {
		this.turnoHora = turnoHora;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
