package com.sisprom.framework.dominio;

// Generated 11-feb-2015 11:06:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int usuarioId;
	private Permiso permiso;
	private String usuarioNombre;
	private String usuarioApellido;
	private String usuarioDni;
	private String usuarioTelefono;
	private String usuarioDomicilioCalle;
	private String usuarioDomicilioNumero;
	private String usuarioDomicilioBarrio;
	private String usuarioRol;
	private String usuarioUsuario;
	private String usuarioContrasenia;
	private String usuarioObraSocial;
	private String usuarioEdad;
	private String usuarioMatricula;
	private String usuarioEspecialidad;
	private Date usuarioHoraAtencionMin;
	private Date usuarioHoraAtencionMax;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Set historiaClinicas = new HashSet(0);
	private Boolean usuarioVisible;
	public Usuario() {
	}

	public Usuario(int usuarioId) {
		this.usuarioId = usuarioId;
	}


	public Usuario(int usuarioId, Permiso permiso, String usuarioNombre,
			String usuarioApellido, String usuarioDni, String usuarioTelefono,
			String usuarioDomicilioBarrio, String usuarioUsuario,
			String usuarioContrasenia, String usuarioRol,
			String usuarioObraSocial, String usuarioEdad,
			String usuarioMatricula, String usuarioEspecialidad,
			Date usuarioHoraAtencionMin, Date usuarioHoraAtencionMax,
			Date fechaCreacion, Date fechaModificacion, String usuarioCreacion,
			String usuarioModificacion, String usuarioDomicilioCalle,
			String usuarioDomicilioNumero) {
		super();
		this.usuarioId = usuarioId;
		this.permiso = permiso;
		this.usuarioNombre = usuarioNombre;
		this.usuarioApellido = usuarioApellido;
		this.usuarioDni = usuarioDni;
		this.usuarioTelefono = usuarioTelefono;
		this.usuarioDomicilioBarrio = usuarioDomicilioBarrio;
		this.usuarioUsuario = usuarioUsuario;
		this.usuarioContrasenia = usuarioContrasenia;
		this.usuarioRol = usuarioRol;
		this.usuarioObraSocial = usuarioObraSocial;
		this.usuarioEdad = usuarioEdad;
		this.usuarioMatricula = usuarioMatricula;
		this.usuarioEspecialidad = usuarioEspecialidad;
		this.usuarioHoraAtencionMin = usuarioHoraAtencionMin;
		this.usuarioHoraAtencionMax = usuarioHoraAtencionMax;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.usuarioDomicilioCalle = usuarioDomicilioCalle;
		this.usuarioDomicilioNumero = usuarioDomicilioNumero;
	}

	public Usuario(int usuarioId, String usuarioNombre, String usuarioApellido,
			String usuarioDni, String usuarioTelefono,
			String usuarioDomicilioBarrio, String usuarioUsuario,
			String usuarioContrasenia, String usuarioRol,
			String usuarioObraSocial, String usuarioEdad,
			String usuarioMatricula, String usuarioEspecialidad,
			Date usuarioHoraAtencionMin, Date usuarioHoraAtencionMax,
			Date fechaCreacion, Date fechaModificacion, String usuarioCreacion,
			String usuarioModificacion, String usuarioDomicilioCalle,
			String usuarioDomicilioNumero) {
		super();
		this.usuarioId = usuarioId;
		this.usuarioNombre = usuarioNombre;
		this.usuarioApellido = usuarioApellido;
		this.usuarioDni = usuarioDni;
		this.usuarioTelefono = usuarioTelefono;
		this.usuarioDomicilioBarrio = usuarioDomicilioBarrio;
		this.usuarioUsuario = usuarioUsuario;
		this.usuarioContrasenia = usuarioContrasenia;
		this.usuarioRol = usuarioRol;
		this.usuarioObraSocial = usuarioObraSocial;
		this.usuarioEdad = usuarioEdad;
		this.usuarioMatricula = usuarioMatricula;
		this.usuarioEspecialidad = usuarioEspecialidad;
		this.usuarioHoraAtencionMin = usuarioHoraAtencionMin;
		this.usuarioHoraAtencionMax = usuarioHoraAtencionMax;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.usuarioDomicilioCalle = usuarioDomicilioCalle;
		this.usuarioDomicilioNumero = usuarioDomicilioNumero;
	}
	public int getRowKey() { return this.hashCode(); }
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	public String getUsuarioNombre() {
		return this.usuarioNombre;
	}

	public void setUsuarioNombre(String usuarioNombre) {
		this.usuarioNombre = usuarioNombre;
	}

	public String getUsuarioApellido() {
		return this.usuarioApellido;
	}

	public void setUsuarioApellido(String usuarioApellido) {
		this.usuarioApellido = usuarioApellido;
	}

	public String getUsuarioDni() {
		return this.usuarioDni;
	}

	public void setUsuarioDni(String usuarioDni) {
		this.usuarioDni = usuarioDni;
	}

	public String getUsuarioTelefono() {
		return this.usuarioTelefono;
	}

	public void setUsuarioTelefono(String usuarioTelefono) {
		this.usuarioTelefono = usuarioTelefono;
	}

	public String getUsuarioDomicilioBarrio() {
		return this.usuarioDomicilioBarrio;
	}

	public void setUsuarioDomicilioBarrio(String usuarioDomicilioBarrio) {
		this.usuarioDomicilioBarrio = usuarioDomicilioBarrio;
	}

	public String getUsuarioUsuario() {
		return this.usuarioUsuario;
	}

	public void setUsuarioUsuario(String usuarioUsuario) {
		this.usuarioUsuario = usuarioUsuario;
	}

	public String getUsuarioContrasenia() {
		return this.usuarioContrasenia;
	}

	public void setUsuarioContrasenia(String usuarioContrasenia) {
		this.usuarioContrasenia = usuarioContrasenia;
	}

	public String getUsuarioRol() {
		return this.usuarioRol;
	}

	public void setUsuarioRol(String usuarioRol) {
		this.usuarioRol = usuarioRol;
	}

	public String getUsuarioObraSocial() {
		return this.usuarioObraSocial;
	}

	public void setUsuarioObraSocial(String usuarioObraSocial) {
		this.usuarioObraSocial = usuarioObraSocial;
	}

	public String getUsuarioEdad() {
		return this.usuarioEdad;
	}

	public void setUsuarioEdad(String usuarioEdad) {
		this.usuarioEdad = usuarioEdad;
	}

	public String getUsuarioMatricula() {
		return this.usuarioMatricula;
	}

	public void setUsuarioMatricula(String usuarioMatricula) {
		this.usuarioMatricula = usuarioMatricula;
	}

	public String getUsuarioEspecialidad() {
		return this.usuarioEspecialidad;
	}

	public void setUsuarioEspecialidad(String usuarioEspecialidad) {
		this.usuarioEspecialidad = usuarioEspecialidad;
	}

	public Date getUsuarioHoraAtencionMin() {
		return this.usuarioHoraAtencionMin;
	}

	public void setUsuarioHoraAtencionMin(Date usuarioHoraAtencionMin) {
		this.usuarioHoraAtencionMin = usuarioHoraAtencionMin;
	}

	public Date getUsuarioHoraAtencionMax() {
		return this.usuarioHoraAtencionMax;
	}

	public void setUsuarioHoraAtencionMax(Date usuarioHoraAtencionMax) {
		this.usuarioHoraAtencionMax = usuarioHoraAtencionMax;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public String getUsuarioDomicilioCalle() {
		return this.usuarioDomicilioCalle;
	}

	public void setUsuarioDomicilioCalle(String usuarioDomicilioCalle) {
		this.usuarioDomicilioCalle = usuarioDomicilioCalle;
	}

	public String getUsuarioDomicilioNumero() {
		return this.usuarioDomicilioNumero;
	}

	public void setUsuarioDomicilioNumero(String usuarioDomicilioNumero) {
		this.usuarioDomicilioNumero = usuarioDomicilioNumero;
	}

	public Set getHistoriaClinicas() {
		return this.historiaClinicas;
	}

	public void setHistoriaClinicas(Set historiaClinicas) {
		this.historiaClinicas = historiaClinicas;
	}

	public Boolean getUsuarioVisible() {
		return usuarioVisible;
	}

	public void setUsuarioVisible(Boolean usuarioVisible) {
		this.usuarioVisible = usuarioVisible;
	}

}
