CREATE TABLE  "PACIENTE" 
   (	"PACIENTE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PACIENTE_NOMBRE" VARCHAR2(100), 
	"PACIENTE_APELLIDO" VARCHAR2(100), 
	"PACIENTE_DNI" VARCHAR2(50), 
	"PACIENTE_TELEFONO" VARCHAR2(50), 
	"PACIENTE_DOMICILIO_CALLE" VARCHAR2(50), 
	"PACIENTE_OBRA_SOCIAL" VARCHAR2(100), 
	"PACIENTE_EDAD" VARCHAR2(3), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	"PACIENTE_ESTADO_CIVIL" VARCHAR2(20), 
	"PACIENTE_FECHA_NACIMIENTO" DATE, 
	"PACIENTE_SEXO" VARCHAR2(20), 
	"PACIENTE_LUGAR_NACIMIENTO" VARCHAR2(50), 
	"PACIENTE_PROFESION" VARCHAR2(50), 
	"PACIENTE_NUMERO_AFILIADO" VARCHAR2(20), 
	"PACIENTE_DOMICILIO_NUMERO" VARCHAR2(50), 
	"PACIENTE_DOMICILIO_BARRIO" VARCHAR2(50), 
	"PACIENTE_VISIBLE" NUMBER(1,0), 
	 CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("PACIENTE_ID") ENABLE
   )
/
CREATE TABLE  "USUARIO" 
   (	"USUARIO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PERMISO_ID" NUMBER(8,0), 
	"USUARIO_NOMBRE" VARCHAR2(100), 
	"USUARIO_APELLIDO" VARCHAR2(100), 
	"USUARIO_DNI" VARCHAR2(50), 
	"USUARIO_TELEFONO" VARCHAR2(50), 
	"USUARIO_DOMICILIO_BARRIO" VARCHAR2(50), 
	"USUARIO_USUARIO" VARCHAR2(50), 
	"USUARIO_CONTRASENIA" VARCHAR2(20), 
	"USUARIO_ROL" VARCHAR2(20), 
	"USUARIO_OBRA_SOCIAL" VARCHAR2(20), 
	"USUARIO_EDAD" VARCHAR2(3), 
	"USUARIO_MATRICULA" VARCHAR2(10), 
	"USUARIO_ESPECIALIDAD" VARCHAR2(20), 
	"USUARIO_HORA_ATENCION_MIN" DATE, 
	"USUARIO_HORA_ATENCION_MAX" DATE, 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"USUARIO_DOMICILIO_CALLE" VARCHAR2(50), 
	"USUARIO_DOMICILIO_NUMERO" VARCHAR2(50), 
	"USUARIO_VISIBLE" NUMBER(1,0), 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("USUARIO_ID") ENABLE, 
	 CONSTRAINT "USUARIO_PERMISO_FK1" FOREIGN KEY ("PERMISO_ID")
	  REFERENCES  "PERMISO" ("PERMISO_ID") ENABLE
   )
/
CREATE TABLE  "HISTORIA_CLINICA" 
   (	"HISTORIA_CLINICA_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PACIENTE_ID" NUMBER(8,0), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_ID" NUMBER(8,0), 
	 CONSTRAINT "HISTORIA_CLINICA_PK" PRIMARY KEY ("HISTORIA_CLINICA_ID") ENABLE, 
	 CONSTRAINT "HISTORIA_CLINICA_PACIENTE_FK1" FOREIGN KEY ("PACIENTE_ID")
	  REFERENCES  "PACIENTE" ("PACIENTE_ID") ENABLE, 
	 CONSTRAINT "HISTORIA_CLINICA_USUARIO_FK1" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES  "USUARIO" ("USUARIO_ID") ENABLE
   )
/
CREATE TABLE  "ANTECEDENTE_GENERAL" 
   (	"ANTECEDENTE_GRAL_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"ANTECEDENTE_PESOALNACER" VARCHAR2(20), 
	"USUARIO_CREACION" VARCHAR2(20), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20), 
	"FECHA_MODIFICACION" DATE, 
	"ANTECEDENTE_TALLA" VARCHAR2(20), 
	"ANTECEDENTE_CCEFALIC" VARCHAR2(20), 
	"ANTECEDENTE_PARTO_NORMAL" VARCHAR2(20), 
	"ANTECEDENTE_PARTO_DISTOCICO" VARCHAR2(20), 
	"ANTECEDENTE_PARTO_CESARIA" VARCHAR2(20), 
	"ANTECEDENTE_COMPLICACIONES" VARCHAR2(20), 
	"ANTECEDENTE_SCOREDEAPGAR" VARCHAR2(20), 
	"ANTECEDENTE_SOCIO_ECONOMICO" VARCHAR2(20), 
	"ANTECEDENTE_DIABETES" VARCHAR2(20), 
	"ANTECEDENTE_ASMA" VARCHAR2(20), 
	"ANTECEDENTE_TBC" VARCHAR2(20), 
	"ANTECEDENTE_HIPERTENSION" VARCHAR2(20), 
	"ANTECEDENTE_PADRE" VARCHAR2(20), 
	"ANTECEDENTE_MADRE" VARCHAR2(20), 
	"ANTECEDENTE_HIJOS" VARCHAR2(20), 
	"ANTECEDENTE_HERMANOS" VARCHAR2(20), 
	"ANTECEDENTE_TABACO" VARCHAR2(20), 
	"ANTECEDENTE_ALCOHOL" VARCHAR2(20), 
	"ANTECEDENTE_ADICCION" VARCHAR2(20), 
	"ANTECEDENTE_OPERACIONANTERIOR" DATE, 
	"ANTECEDENTE_TIPOOPERACION" VARCHAR2(20), 
	"ANTECEDENTE_TRAUMATISMOS" DATE, 
	"ANTECEDENTE_LOCALIZACION" VARCHAR2(20), 
	"ANTECEDENTE_PESO" VARCHAR2(20), 
	"ANTECEDENTE_GENERAL_TALLA" VARCHAR2(20), 
	"ANTECEDENTE_TENSIONARTERIAL" VARCHAR2(20), 
	"ANTECEDENTE_PIELYFANERAS" VARCHAR2(20), 
	"ANTECEDENTE_VISION" VARCHAR2(20), 
	"ANTECEDENTE_AUDICION" VARCHAR2(20), 
	"ANTECEDENTE_ODONTOLOGIA" VARCHAR2(20), 
	"ANTECEDENTE_OBESIDAD" VARCHAR2(20), 
	"ANTECEDENTE_PESONORMAL" VARCHAR2(20), 
	"ANTECEDENTE_PESOBAJO" VARCHAR2(20), 
	"ANTECEDENTE_REACCION_ADVERSA" VARCHAR2(20), 
	 CONSTRAINT "ANTECEDENTE_GRAL_PK" PRIMARY KEY ("ANTECEDENTE_GRAL_ID") ENABLE, 
	 CONSTRAINT "ANTECEDENTE_GENERAL_HISTO_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
	  REFERENCES  "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE
   )
/
CREATE TABLE  "PATOLOGIA" 
   (	"PATOLOGIA_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PATOLOGIA_NOMBRE" VARCHAR2(50), 
	"PATOLOGIA_DESCRIPCION" VARCHAR2(200), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	 CONSTRAINT "PATOLOGIA_PK" PRIMARY KEY ("PATOLOGIA_ID") ENABLE
   )
/
CREATE TABLE  "DETALLE_PATOLOGIA" 
   (	"DETALLE_PAT_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PATOLOGIA_ID" NUMBER(8,0), 
	"DETALLE_PAT_NOMBRE" VARCHAR2(20), 
	"DETALLE_PAT_DESCRIPCION" VARCHAR2(200), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	 CONSTRAINT "DETALLE_PAT_PK" PRIMARY KEY ("DETALLE_PAT_ID") ENABLE, 
	 CONSTRAINT "DETALLE_PATOLOGIA_PATOLOG_FK1" FOREIGN KEY ("PATOLOGIA_ID")
	  REFERENCES  "PATOLOGIA" ("PATOLOGIA_ID") ENABLE
   )
/
CREATE TABLE  "ANTECEDENTE_PER_PATOLOGICO" 
   (	"ANTECEDENTE_PER_PAT_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"ANTECEDENTE_PER_NOMBRE" VARCHAR2(20), 
	"ANTECEDENTE_PER_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(20), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20), 
	"FECHA_MODIFICACION" DATE, 
	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"DETALLE_PAT_ID" NUMBER(8,0), 
	 CONSTRAINT "ANTECEDENTE_PER_PAT_PK" PRIMARY KEY ("ANTECEDENTE_PER_PAT_ID") ENABLE, 
	 CONSTRAINT "ANTECEDENTE_PER_PATOLOGIC_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
	  REFERENCES  "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE, 
	 CONSTRAINT "ANTECEDENTE_PER_PATOLOGIC_FK2" FOREIGN KEY ("DETALLE_PAT_ID")
	  REFERENCES  "DETALLE_PATOLOGIA" ("DETALLE_PAT_ID") ENABLE
   )
/
CREATE TABLE  "CONSULTA" 
   (	"CONSULTA_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"CONSULTA_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(20), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20), 
	"FECHA_MODIFICACION" DATE, 
	"CONSULTA_FECHA" DATE, 
	"CONSULTA_EXAMEN_FISICO" VARCHAR2(200), 
	"CONSULTA_EVOLUCION" VARCHAR2(200), 
	 CONSTRAINT "CONSULTA_PK" PRIMARY KEY ("CONSULTA_ID") ENABLE, 
	 CONSTRAINT "CONSULTA_HISTORIA_CLINICA_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
	  REFERENCES  "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE
   )
/
CREATE TABLE  "DIAGNOSTICO" 
   (	"DIAGNOSTICO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"CONSULTA_ID" NUMBER(8,0), 
	"DIAGNOSTICO_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "DIAGNOSTICO_PK" PRIMARY KEY ("DIAGNOSTICO_ID") ENABLE, 
	 CONSTRAINT "DIAGNOSTICO_CONSULTA_FK1" FOREIGN KEY ("CONSULTA_ID")
	  REFERENCES  "CONSULTA" ("CONSULTA_ID") ENABLE
   )
/
CREATE TABLE  "MEDICAMENTO" 
   (	"MEDICAMENTO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"MEDICAMENTO_NOMBRE" VARCHAR2(100), 
	"MEDICAMENTO_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "MEDICAMENTO_PK" PRIMARY KEY ("MEDICAMENTO_ID") ENABLE
   )
/
CREATE TABLE  "PERMISO" 
   (	"PERMISO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PERMISO_NOMBRE" VARCHAR2(20), 
	"PERMISO_PERMISO" VARCHAR2(50), 
	"PERMISO_DESCRIPCION" VARCHAR2(250), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	 CONSTRAINT "PERMISO_PK" PRIMARY KEY ("PERMISO_ID") ENABLE
   )
/
CREATE TABLE  "TRATAMIENTO" 
   (	"TRATAMIENTO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"DIAGNOSTICO_ID" NUMBER(8,0), 
	"TRATAMIENTO_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "TRATAMIENTO_PK" PRIMARY KEY ("TRATAMIENTO_ID") ENABLE, 
	 CONSTRAINT "TRATAMIENTO_DIAGNOSTICO_FK1" FOREIGN KEY ("DIAGNOSTICO_ID")
	  REFERENCES  "DIAGNOSTICO" ("DIAGNOSTICO_ID") ENABLE
   )
/
CREATE TABLE  "TRATAMIENTO_MEDICAMENTO" 
   (	"TRATAMIENTO_MEDICAMENTO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"MEDICAMENTO_ID" NUMBER(8,0), 
	"TRATAMIENTO_ID" NUMBER(8,0), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "TRATAMIENTO_MEDICAMENTO_PK" PRIMARY KEY ("TRATAMIENTO_MEDICAMENTO_ID") ENABLE, 
	 CONSTRAINT "TRATAMIENTO_MEDICAMENTO_M_FK1" FOREIGN KEY ("MEDICAMENTO_ID")
	  REFERENCES  "MEDICAMENTO" ("MEDICAMENTO_ID") ENABLE, 
	 CONSTRAINT "TRATAMIENTO_MEDICAMENTO_T_FK1" FOREIGN KEY ("TRATAMIENTO_ID")
	  REFERENCES  "TRATAMIENTO" ("TRATAMIENTO_ID") ENABLE
   )
/
CREATE TABLE  "TURNO" 
   (	"TURNO_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PACIENTE_ID" NUMBER(8,0), 
	"TURNO_FECHA" DATE, 
	"TURNO_HORA" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "TURNO_PK" PRIMARY KEY ("TURNO_ID") ENABLE, 
	 CONSTRAINT "TURNO_PACIENTE_FK1" FOREIGN KEY ("PACIENTE_ID")
	  REFERENCES  "PACIENTE" ("PACIENTE_ID") ENABLE
   )
/

CREATE UNIQUE INDEX  "ANTECEDENTE_GRAL_PK" ON  "ANTECEDENTE_GENERAL" ("ANTECEDENTE_GRAL_ID")
/
CREATE UNIQUE INDEX  "ANTECEDENTE_PER_PAT_PK" ON  "ANTECEDENTE_PER_PATOLOGICO" ("ANTECEDENTE_PER_PAT_ID")
/
CREATE UNIQUE INDEX  "CONSULTA_PK" ON  "CONSULTA" ("CONSULTA_ID")
/
CREATE UNIQUE INDEX  "DETALLE_PAT_PK" ON  "DETALLE_PATOLOGIA" ("DETALLE_PAT_ID")
/
CREATE UNIQUE INDEX  "DIAGNOSTICO_PK" ON  "DIAGNOSTICO" ("DIAGNOSTICO_ID")
/
CREATE UNIQUE INDEX  "HISTORIA_CLINICA_PK" ON  "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/
CREATE UNIQUE INDEX  "MEDICAMENTO_PK" ON  "MEDICAMENTO" ("MEDICAMENTO_ID")
/
CREATE UNIQUE INDEX  "PACIENTE_PK" ON  "PACIENTE" ("PACIENTE_ID")
/
CREATE UNIQUE INDEX  "PATOLOGIA_PK" ON  "PATOLOGIA" ("PATOLOGIA_ID")
/
CREATE UNIQUE INDEX  "PERMISO_PK" ON  "PERMISO" ("PERMISO_ID")
/
CREATE UNIQUE INDEX  "TRATAMIENTO_MEDICAMENTO_PK" ON  "TRATAMIENTO_MEDICAMENTO" ("TRATAMIENTO_MEDICAMENTO_ID")
/
CREATE UNIQUE INDEX  "TRATAMIENTO_PK" ON  "TRATAMIENTO" ("TRATAMIENTO_ID")
/
CREATE UNIQUE INDEX  "TURNO_PK" ON  "TURNO" ("TURNO_ID")
/
CREATE UNIQUE INDEX  "USUARIO_PK" ON  "USUARIO" ("USUARIO_ID")
/

Rem No se ha encontrado package para generar DDL.

 CREATE SEQUENCE   "ADMINISTRADOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ANTECEDENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "CONSULTA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DIAGNOSTICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "HISTORIA_CLINICA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MEDICAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MEDICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "PACIENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "SECRETARIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "TIPO_ANTECEDENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "TRATAMIENTO_MEDICAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "TRATAMIENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "TURNO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
