--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-05-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMINISTRADOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."ADMINISTRADOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ANTECEDENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."ANTECEDENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONSULTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."CONSULTA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DIAGNOSTICO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."DIAGNOSTICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HISTORIA_CLINICA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."HISTORIA_CLINICA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEDICAMENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."MEDICAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEDICO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."MEDICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PACIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."PACIENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SECRETARIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."SECRETARIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_ANTECEDENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."TIPO_ANTECEDENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRATAMIENTO_MEDICAMENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."TRATAMIENTO_MEDICAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRATAMIENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."TRATAMIENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TURNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SISPROM2"."TURNO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ANTECEDENTE_GENERAL
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."ANTECEDENTE_GENERAL" 
   (	"ANTECEDENTE_GRAL_ID" NUMBER(20,0), 
	"HISTORIA_CLINICA_ID" NUMBER(20,0), 
	"ANTECEDENTE_PESOALNACER" VARCHAR2(50 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"ANTECEDENTE_TALLA" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_CCEFALIC" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PARTO_NORMAL" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PARTO_DISTOCICO" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PARTO_CESARIA" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_COMPLICACIONES" VARCHAR2(50 BYTE), 
	"ANTECEDENTE_SCOREDEAPGAR" VARCHAR2(50 BYTE), 
	"ANTECEDENTE_SOCIO_ECONOMICO" VARCHAR2(200 BYTE), 
	"ANTECEDENTE_DIABETES" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_ASMA" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_TBC" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_HIPERTENSION" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PADRE" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_MADRE" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_HIJOS" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_HERMANOS" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_TABACO" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_ALCOHOL" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_ADICCION" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_OPERACIONANTERIOR" DATE, 
	"ANTECEDENTE_TIPOOPERACION" VARCHAR2(50 BYTE), 
	"ANTECEDENTE_TRAUMATISMOS" DATE, 
	"ANTECEDENTE_LOCALIZACION" VARCHAR2(50 BYTE), 
	"ANTECEDENTE_PESO" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_GENERAL_TALLA" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_TENSIONARTERIAL" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PIELYFANERAS" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_VISION" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_AUDICION" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_ODONTOLOGIA" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_OBESIDAD" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PESONORMAL" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_PESOBAJO" VARCHAR2(20 BYTE), 
	"ANTECEDENTE_REACCION_ADVERSA" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ANTECEDENTE_PER_PATOLOGICO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."ANTECEDENTE_PER_PATOLOGICO" 
   (	"ANTECEDENTE_PER_PAT_ID" NUMBER(20,0), 
	"ANTECEDENTE_PER_NOMBRE" VARCHAR2(100 BYTE), 
	"ANTECEDENTE_PER_DESCRIPCION" VARCHAR2(200 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"DETALLE_PATOLOGIA_ID" VARCHAR2(20 BYTE), 
	"HISTORIA_CLINICA_ID" NUMBER, 
	"DETALLE_PAT_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSULTA
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."CONSULTA" 
   (	"CONSULTA_ID" NUMBER(20,0), 
	"HISTORIA_CLINICA_ID" NUMBER(20,0), 
	"CONSULTA_DESCRIPCION" VARCHAR2(200 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"CONSULTA_FECHA" DATE, 
	"CONSULTA_EXAMEN_FISICO" VARCHAR2(200 BYTE), 
	"CONSULTA_EVOLUCION" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_PATOLOGIA
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."DETALLE_PATOLOGIA" 
   (	"DETALLE_PAT_ID" NUMBER, 
	"PATOLOGIA_ID" NUMBER, 
	"DETALLE_PAT_NOMBRE" VARCHAR2(20 BYTE), 
	"DETALLE_PAT_DESCRIPCION" VARCHAR2(200 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIAGNOSTICO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."DIAGNOSTICO" 
   (	"DIAGNOSTICO_ID" NUMBER(20,0), 
	"CONSULTA_ID" NUMBER(20,0), 
	"DIAGNOSTICO_DESCRIPCION" VARCHAR2(200 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORIA_CLINICA
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."HISTORIA_CLINICA" 
   (	"HISTORIA_CLINICA_ID" NUMBER(20,0), 
	"PACIENTE_ID" NUMBER(20,0), 
	"HISTORIA_CLINICA_DESCRIPCION" VARCHAR2(200 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_ID" NUMBER(20,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."MEDICAMENTO" 
   (	"MEDICAMENTO_ID" NUMBER(20,0), 
	"MEDICAMENTO_NOMBRE" VARCHAR2(100 BYTE), 
	"MEDICAMENTO_DESCRIPCION" VARCHAR2(200 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."PACIENTE" 
   (	"PACIENTE_ID" NUMBER(20,0), 
	"PACIENTE_NOMBRE" VARCHAR2(100 BYTE), 
	"PACIENTE_APELLIDO" VARCHAR2(100 BYTE), 
	"PACIENTE_DNI" VARCHAR2(50 BYTE), 
	"PACIENTE_TELEFONO" VARCHAR2(50 BYTE), 
	"PACIENTE_DOMICILIO_CALLE" VARCHAR2(50 BYTE), 
	"PACIENTE_OBRA_SOCIAL" VARCHAR2(100 BYTE), 
	"PACIENTE_EDAD" VARCHAR2(3 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"PACIENTE_ESTADO_CIVIL" VARCHAR2(20 BYTE), 
	"PACIENTE_FECHA_NACIMIENTO" DATE, 
	"PACIENTE_SEXO" VARCHAR2(20 BYTE), 
	"PACIENTE_LUGAR_NACIMIENTO" VARCHAR2(50 BYTE), 
	"PACIENTE_PROFESION" VARCHAR2(50 BYTE), 
	"PACIENTE_NUMERO_AFILIADO" VARCHAR2(20 BYTE), 
	"PACIENTE_DOMICILIO_NUMERO" VARCHAR2(50 BYTE), 
	"PACIENTE_DOMICILIO_BARRIO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATOLOGIA
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."PATOLOGIA" 
   (	"PATOLOGIA_ID" NUMBER, 
	"PATOLOGIA_NOMBRE" VARCHAR2(50 BYTE), 
	"PATOLOGIA_DESCRIPCION" VARCHAR2(200 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERMISO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."PERMISO" 
   (	"PERMISO_ID" NUMBER(20,0), 
	"PERMISO_NOMBRE" VARCHAR2(20 BYTE), 
	"PERMISO_PERMISO" VARCHAR2(50 BYTE), 
	"PERMISO_DESCRIPCION" VARCHAR2(250 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRATAMIENTO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."TRATAMIENTO" 
   (	"TRATAMIENTO_ID" NUMBER(20,0), 
	"DIAGNOSTICO_ID" NUMBER(20,0), 
	"TRATAMIENTO_NOMBRE" VARCHAR2(100 BYTE), 
	"TRATAMIENTO_DESCRIPCION" VARCHAR2(200 BYTE), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRATAMIENTO_MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."TRATAMIENTO_MEDICAMENTO" 
   (	"TRATAMIENTO_MEDICAMENTO_ID" NUMBER(20,0), 
	"MEDICAMENTO_ID" NUMBER(20,0), 
	"TRATAMIENTO_ID" NUMBER(20,0), 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TURNO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."TURNO" 
   (	"TURNO_ID" NUMBER(20,0), 
	"PACIENTE_ID" NUMBER(20,0), 
	"TURNO_FECHA" DATE, 
	"TURNO_HORA" DATE, 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SISPROM2"."USUARIO" 
   (	"USUARIO_ID" NUMBER(20,0), 
	"PERMISO_ID" NUMBER(20,0), 
	"USUARIO_NOMBRE" VARCHAR2(100 BYTE), 
	"USUARIO_APELLIDO" VARCHAR2(100 BYTE), 
	"USUARIO_DNI" VARCHAR2(50 BYTE), 
	"USUARIO_TELEFONO" VARCHAR2(50 BYTE), 
	"USUARIO_DOMICILIO_BARRIO" VARCHAR2(50 BYTE), 
	"USUARIO_USUARIO" VARCHAR2(50 BYTE), 
	"USUARIO_CONTRASENIA" VARCHAR2(20 BYTE), 
	"USUARIO_ROLL" VARCHAR2(20 BYTE), 
	"USUARIO_OBRA_SOCIAL" VARCHAR2(20 BYTE), 
	"USUARIO_OBRASOCIAL" VARCHAR2(20 BYTE), 
	"USUARIO_EDAD" VARCHAR2(3 BYTE), 
	"USUARIO_MATRICULA" VARCHAR2(10 BYTE), 
	"USUARIO_ESPECIALIDAD" VARCHAR2(20 BYTE), 
	"USUARIO_HORA_ATENCION_MIN" DATE, 
	"USUARIO_HORA_ATENCION_MAX" DATE, 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100 BYTE), 
	"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
	"USUARIO_DOMICILIO_CALLE" VARCHAR2(50 BYTE), 
	"USUARIO_DOMICILIO_NUMERO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SISPROM2.ANTECEDENTE_GENERAL
SET DEFINE OFF;
REM INSERTING into SISPROM2.ANTECEDENTE_PER_PATOLOGICO
SET DEFINE OFF;
REM INSERTING into SISPROM2.CONSULTA
SET DEFINE OFF;
REM INSERTING into SISPROM2.DETALLE_PATOLOGIA
SET DEFINE OFF;
REM INSERTING into SISPROM2.DIAGNOSTICO
SET DEFINE OFF;
REM INSERTING into SISPROM2.HISTORIA_CLINICA
SET DEFINE OFF;
REM INSERTING into SISPROM2.MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into SISPROM2.PACIENTE
SET DEFINE OFF;
REM INSERTING into SISPROM2.PATOLOGIA
SET DEFINE OFF;
REM INSERTING into SISPROM2.PERMISO
SET DEFINE OFF;
REM INSERTING into SISPROM2.TRATAMIENTO
SET DEFINE OFF;
REM INSERTING into SISPROM2.TRATAMIENTO_MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into SISPROM2.TURNO
SET DEFINE OFF;
REM INSERTING into SISPROM2.USUARIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ANTECEDENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."ANTECEDENTE_PK" ON "SISPROM2"."ANTECEDENTE_GENERAL" ("ANTECEDENTE_GRAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONSULTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."CONSULTA_PK" ON "SISPROM2"."CONSULTA" ("CONSULTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_PATOLOGIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."DETALLE_PATOLOGIA_PK" ON "SISPROM2"."DETALLE_PATOLOGIA" ("DETALLE_PAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIAGNOSTICO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."DIAGNOSTICO_PK" ON "SISPROM2"."DIAGNOSTICO" ("DIAGNOSTICO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HISTORIA_CLINICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."HISTORIA_CLINICA_PK" ON "SISPROM2"."HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEDICAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."MEDICAMENTO_PK" ON "SISPROM2"."MEDICAMENTO" ("MEDICAMENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PACIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."PACIENTE_PK" ON "SISPROM2"."PACIENTE" ("PACIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PATOLOGIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."PATOLOGIA_PK" ON "SISPROM2"."PATOLOGIA" ("PATOLOGIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERMISO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."PERMISO_PK" ON "SISPROM2"."PERMISO" ("PERMISO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_ANTECEDENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."TIPO_ANTECEDENTE_PK" ON "SISPROM2"."ANTECEDENTE_PER_PATOLOGICO" ("ANTECEDENTE_PER_PAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRATAMIENTO_MEDICAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."TRATAMIENTO_MEDICAMENTO_PK" ON "SISPROM2"."TRATAMIENTO_MEDICAMENTO" ("TRATAMIENTO_MEDICAMENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRATAMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."TRATAMIENTO_PK" ON "SISPROM2"."TRATAMIENTO" ("TRATAMIENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TURNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."TURNO_PK" ON "SISPROM2"."TURNO" ("TURNO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISPROM2"."USUARIO_PK" ON "SISPROM2"."USUARIO" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANTECEDENTE_GENERAL
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."ANTECEDENTE_GENERAL" ADD CONSTRAINT "ANTECEDENTE_PK" PRIMARY KEY ("ANTECEDENTE_GRAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."ANTECEDENTE_GENERAL" MODIFY ("ANTECEDENTE_GRAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANTECEDENTE_PER_PATOLOGICO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."ANTECEDENTE_PER_PATOLOGICO" MODIFY ("ANTECEDENTE_PER_PAT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SISPROM2"."ANTECEDENTE_PER_PATOLOGICO" ADD CONSTRAINT "TIPO_ANTECEDENTE_PK" PRIMARY KEY ("ANTECEDENTE_PER_PAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSULTA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."CONSULTA" ADD CONSTRAINT "CONSULTA_PK" PRIMARY KEY ("CONSULTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."CONSULTA" MODIFY ("CONSULTA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_PATOLOGIA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."DETALLE_PATOLOGIA" ADD CONSTRAINT "DETALLE_PATOLOGIA_PK" PRIMARY KEY ("DETALLE_PAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."DETALLE_PATOLOGIA" MODIFY ("DETALLE_PAT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIAGNOSTICO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."DIAGNOSTICO" ADD CONSTRAINT "DIAGNOSTICO_PK" PRIMARY KEY ("DIAGNOSTICO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."DIAGNOSTICO" MODIFY ("DIAGNOSTICO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORIA_CLINICA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."HISTORIA_CLINICA" ADD CONSTRAINT "HISTORIA_CLINICA_PK" PRIMARY KEY ("HISTORIA_CLINICA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."HISTORIA_CLINICA" MODIFY ("HISTORIA_CLINICA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_PK" PRIMARY KEY ("MEDICAMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."MEDICAMENTO" MODIFY ("MEDICAMENTO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."PACIENTE" ADD CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("PACIENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."PACIENTE" MODIFY ("PACIENTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATOLOGIA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."PATOLOGIA" ADD CONSTRAINT "PATOLOGIA_PK" PRIMARY KEY ("PATOLOGIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."PATOLOGIA" MODIFY ("PATOLOGIA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERMISO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."PERMISO" ADD CONSTRAINT "PERMISO_PK" PRIMARY KEY ("PERMISO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SISPROM2"."PERMISO" MODIFY ("PERMISO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRATAMIENTO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."TRATAMIENTO" MODIFY ("TRATAMIENTO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SISPROM2"."TRATAMIENTO" ADD CONSTRAINT "TRATAMIENTO_PK" PRIMARY KEY ("TRATAMIENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRATAMIENTO_MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."TRATAMIENTO_MEDICAMENTO" MODIFY ("TRATAMIENTO_MEDICAMENTO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SISPROM2"."TRATAMIENTO_MEDICAMENTO" ADD CONSTRAINT "TRATAMIENTO_MEDICAMENTO_PK" PRIMARY KEY ("TRATAMIENTO_MEDICAMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TURNO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."TURNO" MODIFY ("TURNO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SISPROM2"."TURNO" ADD CONSTRAINT "TURNO_PK" PRIMARY KEY ("TURNO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."USUARIO" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SISPROM2"."USUARIO" MODIFY ("PERMISO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SISPROM2"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANTECEDENTE_GENERAL
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."ANTECEDENTE_GENERAL" ADD CONSTRAINT "ANT_HIST_CLIN_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
	  REFERENCES "SISPROM2"."HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANTECEDENTE_PER_PATOLOGICO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."ANTECEDENTE_PER_PATOLOGICO" ADD CONSTRAINT "ANTECEDENTES_PER_PATOLOGI_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
	  REFERENCES "SISPROM2"."HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE;
 
  ALTER TABLE "SISPROM2"."ANTECEDENTE_PER_PATOLOGICO" ADD CONSTRAINT "ANTECEDENTES_PER_PATOLOGI_FK2" FOREIGN KEY ("DETALLE_PAT_ID")
	  REFERENCES "SISPROM2"."DETALLE_PATOLOGIA" ("DETALLE_PAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSULTA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."CONSULTA" ADD CONSTRAINT "CONSULTA_HISTORIA_CLINICA_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
	  REFERENCES "SISPROM2"."HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_PATOLOGIA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."DETALLE_PATOLOGIA" ADD CONSTRAINT "DETALLE_PATOLOGIA_PATOLOG_FK1" FOREIGN KEY ("PATOLOGIA_ID")
	  REFERENCES "SISPROM2"."PATOLOGIA" ("PATOLOGIA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIAGNOSTICO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."DIAGNOSTICO" ADD CONSTRAINT "DIAGNOSTICO_CONSULTA_FK1" FOREIGN KEY ("CONSULTA_ID")
	  REFERENCES "SISPROM2"."CONSULTA" ("CONSULTA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIA_CLINICA
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."HISTORIA_CLINICA" ADD CONSTRAINT "HISTORIA_CLINICA_PACIENTE_FK1" FOREIGN KEY ("PACIENTE_ID")
	  REFERENCES "SISPROM2"."PACIENTE" ("PACIENTE_ID") ENABLE;
 
  ALTER TABLE "SISPROM2"."HISTORIA_CLINICA" ADD CONSTRAINT "HISTORIA_CLINICA_USUARIO_FK1" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "SISPROM2"."USUARIO" ("USUARIO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRATAMIENTO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."TRATAMIENTO" ADD CONSTRAINT "TRATAMIENTO_DIAGNOSTICO_FK1" FOREIGN KEY ("DIAGNOSTICO_ID")
	  REFERENCES "SISPROM2"."DIAGNOSTICO" ("DIAGNOSTICO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRATAMIENTO_MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."TRATAMIENTO_MEDICAMENTO" ADD CONSTRAINT "TRAT_MED_MED_FK1" FOREIGN KEY ("MEDICAMENTO_ID")
	  REFERENCES "SISPROM2"."MEDICAMENTO" ("MEDICAMENTO_ID") ENABLE;
 
  ALTER TABLE "SISPROM2"."TRATAMIENTO_MEDICAMENTO" ADD CONSTRAINT "TRAT_MED_TRAT_FK1" FOREIGN KEY ("TRATAMIENTO_ID")
	  REFERENCES "SISPROM2"."TRATAMIENTO" ("TRATAMIENTO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TURNO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."TURNO" ADD CONSTRAINT "TURNO_PACIENTE_FK1" FOREIGN KEY ("PACIENTE_ID")
	  REFERENCES "SISPROM2"."PACIENTE" ("PACIENTE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SISPROM2"."USUARIO" ADD CONSTRAINT "USUARIO_PERMISO_FK1" FOREIGN KEY ("PERMISO_ID")
	  REFERENCES "SISPROM2"."PERMISO" ("PERMISO_ID") ENABLE;
