--------------------------------------------------------
--  DDL for Table SECRETARIA
--------------------------------------------------------
  CREATE TABLE "SECRETARIA" 
   (	"SECRETARIA_ID" NUMBER(20,0), 
        "SECRETARIA_NOMBRE" VARCHAR2(100 BYTE),
		"SECRETARIA_APELLIDO" VARCHAR2(100 BYTE),
		"SECRETARIA_DNI" VARCHAR2(50 BYTE),
		"SECRETARIA_TELEFONO" VARCHAR2(50 BYTE),
		"SECRETARIA_DIRECCION" VARCHAR2(100 BYTE), 
		"SECRETARIA_HR_ATENCION_MIN" DATE, 
		"SECRETARIA_HR_ATENCION_MAX" DATE,
		"SECRETARIA_USUARIO" VARCHAR2(50 BYTE),
		"SECRETARIA_CONTRASENIA" VARCHAR2(50 BYTE),	
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "SECRETARIA_PK" ON "SECRETARIA" ("SECRETARIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "SECRETARIA" ADD CONSTRAINT "SECRETARIA_PK" PRIMARY KEY ("SECRETARIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SECRETARIA" MODIFY ("SECRETARIA_ID" NOT NULL ENABLE);
  

    --------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------
  CREATE TABLE "PACIENTE" 
   (	"PACIENTE_ID" NUMBER(20,0), 
        "PACIENTE_NOMBRE" VARCHAR2(100 BYTE),
		"PACIENTE_APELLIDO" VARCHAR2(100 BYTE),
		"PACIENTE_DNI" VARCHAR2(50 BYTE),
		"PACIENTE_TELEFONO" VARCHAR2(50 BYTE),
		"PACIENTE_DIRECCION" VARCHAR2(100 BYTE), 
		"PACIENTE_OBRA_SOCIAL" VARCHAR2(100 BYTE),
		"PACIENTE_EDAD" VARCHAR2(3 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "PACIENTE_PK" ON "PACIENTE" ("PACIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "PACIENTE" ADD CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("PACIENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PACIENTE" MODIFY ("PACIENTE_ID" NOT NULL ENABLE);
  
   --------------------------------------------------------
--  DDL for Table MEDICO
--------------------------------------------------------
  CREATE TABLE "MEDICO" 
   (	"MEDICO_ID" NUMBER(20,0), 
        "MEDICO_NOMBRE" VARCHAR2(100 BYTE),
		"MEDICO_APELLIDO" VARCHAR2(100 BYTE),
		"MEDICO_DNI" VARCHAR2(50 BYTE),
		"MEDICO_TELEFONO" VARCHAR2(50 BYTE),
		"MEDICO_DIRECCION" VARCHAR2(100 BYTE), 
		"MEDICO_MATRICULA" VARCHAR2(50 BYTE),
		"MEDICO_ESPECIALIDAD" VARCHAR2(50 BYTE),
		"MEDICO_HR_ATENCION_MIN" DATE, 
		"MEDICO_HR_ATENCION_MAX" DATE, 
		"MEDICO_USUARIO" VARCHAR2(50 BYTE),
		"MEDICO_CONTRASENIA" VARCHAR2(50 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "MEDICO_PK" ON "MEDICO" ("MEDICO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "MEDICO" ADD CONSTRAINT "MEDICO_PK" PRIMARY KEY ("MEDICO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MEDICO" MODIFY ("MEDICO_ID" NOT NULL ENABLE);
  
  
   --------------------------------------------------------
--  DDL for Table TURNO
--------------------------------------------------------
  CREATE TABLE "TURNO" 
   (	"TURNO_ID" NUMBER(20,0),	
        "PACIENTE_ID" NUMBER(20,0),
		"SECRETARIA_ID" NUMBER(20,0),
		"TURNO_FECHA" DATE,
        "TURNO_HORA" DATE, 			
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "TURNO_PK" ON "TURNO" ("TURNO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "TURNO" ADD CONSTRAINT "TURNO_PK" PRIMARY KEY ("TURNO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TURNO" MODIFY ("TURNO_ID" NOT NULL ENABLE);
  ALTER TABLE "TURNO" ADD CONSTRAINT "TURNO_PACIENTE_FK1" FOREIGN KEY ("PACIENTE_ID")
  REFERENCES "PACIENTE" ("PACIENTE_ID") ENABLE;
  ALTER TABLE "TURNO" ADD CONSTRAINT "TURNO_SECRETARIA_FK1" FOREIGN KEY ("SECRETARIA_ID")
  REFERENCES "SECRETARIA" ("SECRETARIA_ID") ENABLE;
  
     --------------------------------------------------------
--  DDL for Table HISTORIA_CLINICA
--------------------------------------------------------
  CREATE TABLE "HISTORIA_CLINICA" 
   (	"HISTORIA_CLINICA_ID" NUMBER(20,0),
        "MEDICO_ID" NUMBER(20,0),
		"PACIENTE_ID" NUMBER(20,0),
        "HISTORIA_CLINICA_DESCRIPCION" VARCHAR2(200 BYTE),		
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "HISTORIA_CLINICA_PK" ON "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "HISTORIA_CLINICA" ADD CONSTRAINT "HISTORIA_CLINICA_PK" PRIMARY KEY ("HISTORIA_CLINICA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HISTORIA_CLINICA" MODIFY ("HISTORIA_CLINICA_ID" NOT NULL ENABLE);

  ALTER TABLE "HISTORIA_CLINICA" ADD CONSTRAINT "HISTORIA_CLINICA_MEDICO_FK1" FOREIGN KEY ("MEDICO_ID")
  REFERENCES "MEDICO" ("MEDICO_ID") ENABLE;
  ALTER TABLE "HISTORIA_CLINICA" ADD CONSTRAINT "HISTORIA_CLINICA_PACIENTE_FK1" FOREIGN KEY ("PACIENTE_ID")
  REFERENCES "PACIENTE" ("PACIENTE_ID") ENABLE;
  
  --------------------------------------------------------
--  DDL for Table TIPO_ANTECEDENTE
--------------------------------------------------------
CREATE TABLE "TIPO_ANTECEDENTE" 
   (	"TIPO_ANTECEDENTE_ID" NUMBER(20,0), 
		"TIPO_ANTECEDENTE_NOMBRE" VARCHAR2(100 BYTE),
		"TIPO_ANTECEDENTE_DESCRIPCION" VARCHAR2(200 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "TIPO_ANTECEDENTE_PK" ON "TIPO_ANTECEDENTE" ("TIPO_ANTECEDENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  ALTER TABLE "TIPO_ANTECEDENTE" ADD CONSTRAINT "TIPO_ANTECEDENTE_PK" PRIMARY KEY ("TIPO_ANTECEDENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TIPO_ANTECEDENTE" MODIFY ("TIPO_ANTECEDENTE_ID" NOT NULL ENABLE);
  
    --------------------------------------------------------
--  DDL for Table ANTECEDENTE
--------------------------------------------------------
  CREATE TABLE "ANTECEDENTE" 
   (	"ANTECEDENTE_ID" NUMBER(20,0), 
        "HISTORIA_CLINICA_ID" NUMBER(20,0),
		"TIPO_ANTECEDENTE_ID" NUMBER(20,0), 		
		"ANTECEDENTE_DESCRIPION" VARCHAR2(200 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "ANTECEDENTE_PK" ON "ANTECEDENTE" ("ANTECEDENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "ANTECEDENTE" ADD CONSTRAINT "ANTECEDENTE_PK" PRIMARY KEY ("ANTECEDENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANTECEDENTE" MODIFY ("ANTECEDENTE_ID" NOT NULL ENABLE);
  
  ALTER TABLE "ANTECEDENTE" ADD CONSTRAINT "ANT_HIST_CLIN_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
  REFERENCES "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE;
  ALTER TABLE "ANTECEDENTE" ADD CONSTRAINT "ANT_TIPO_ANT_FK1" FOREIGN KEY ("TIPO_ANTECEDENTE_ID")
  REFERENCES "TIPO_ANTECEDENTE" ("TIPO_ANTECEDENTE_ID") ENABLE;
  
     --------------------------------------------------------
--  DDL for Table CONSULTA
--------------------------------------------------------
  CREATE TABLE "CONSULTA" 
   (	"CONSULTA_ID" NUMBER(20,0), 
        "HISTORIA_CLINICA_ID" NUMBER(20,0),		
		"CONSULTA_DESCRIPCION" VARCHAR2(200 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "CONSULTA_PK" ON "CONSULTA" ("CONSULTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "CONSULTA" ADD CONSTRAINT "CONSULTA_PK" PRIMARY KEY ("CONSULTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CONSULTA" MODIFY ("CONSULTA_ID" NOT NULL ENABLE);
  
  ALTER TABLE "CONSULTA" ADD CONSTRAINT "CONSULTA_HISTORIA_CLINICA_FK1" FOREIGN KEY ("HISTORIA_CLINICA_ID")
  REFERENCES "HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID") ENABLE;
      --------------------------------------------------------
--  DDL for Table DIAGNOSTICO 
--------------------------------------------------------
  CREATE TABLE "DIAGNOSTICO" 
   (	"DIAGNOSTICO_ID" NUMBER(20,0), 
        "CONSULTA_ID" NUMBER(20,0),		
		"DIAGNOSTICO_DESCRIPCION" VARCHAR2(200 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "DIAGNOSTICO_PK" ON "DIAGNOSTICO" ("DIAGNOSTICO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "DIAGNOSTICO" ADD CONSTRAINT "DIAGNOSTICO_PK" PRIMARY KEY ("DIAGNOSTICO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DIAGNOSTICO" MODIFY ("DIAGNOSTICO_ID" NOT NULL ENABLE);
  
  ALTER TABLE "DIAGNOSTICO" ADD CONSTRAINT "DIAGNOSTICO_CONSULTA_FK1" FOREIGN KEY ("CONSULTA_ID")
  REFERENCES "CONSULTA" ("CONSULTA_ID") ENABLE;
  
  
     --------------------------------------------------------
--  DDL for Table TRATAMIENTO 
--------------------------------------------------------
  CREATE TABLE "TRATAMIENTO" 
   (	"TRATAMIENTO_ID" NUMBER(20,0), 
        "DIAGNOSTICO_ID" NUMBER(20,0),
		"TRATAMIENTO_NOMBRE" VARCHAR2(100 BYTE),		
		"TRATAMIENTO_DESCRIPCION" VARCHAR2(200 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "TRATAMIENTO_PK" ON "TRATAMIENTO" ("TRATAMIENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "TRATAMIENTO" ADD CONSTRAINT "TRATAMIENTO_PK" PRIMARY KEY ("TRATAMIENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TRATAMIENTO" MODIFY ("TRATAMIENTO_ID" NOT NULL ENABLE);
  
  ALTER TABLE "TRATAMIENTO" ADD CONSTRAINT "TRATAMIENTO_DIAGNOSTICO_FK1" FOREIGN KEY ("DIAGNOSTICO_ID")
  REFERENCES "DIAGNOSTICO" ("DIAGNOSTICO_ID") ENABLE;
  
  --------------------------------------------------------
--  DDL for Table MEDICAMENTO
--------------------------------------------------------
CREATE TABLE "MEDICAMENTO" 
   (	"MEDICAMENTO_ID" NUMBER(20,0), 
		"MEDICAMENTO_NOMBRE" VARCHAR2(100 BYTE),
		"MEDICAMENTO_DESCRIPCION" VARCHAR2(200 BYTE),
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "MEDICAMENTO_PK" ON "MEDICAMENTO" ("MEDICAMENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  ALTER TABLE "MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_PK" PRIMARY KEY ("MEDICAMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MEDICAMENTO" MODIFY ("MEDICAMENTO_ID" NOT NULL ENABLE);

     --------------------------------------------------------
--  DDL for Table TRATAMIENTO_MEDICAMENTO
--------------------------------------------------------
  CREATE TABLE "TRATAMIENTO_MEDICAMENTO" 
   (	"TRATAMIENTO_MEDICAMENTO_ID" NUMBER(20,0), 
        "MEDICAMENTO_ID" NUMBER(20,0),
		"TRATAMIENTO_ID" NUMBER(20,0), 		
		"USUARIO_CREACION" VARCHAR2(100 BYTE),
		"FECHA_CREACION" DATE, 
		"USUARIO_MODIFICACION" VARCHAR2(100 BYTE), 
		"FECHA_MODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "TRATAMIENTO_MEDICAMENTO_PK" ON "TRATAMIENTO_MEDICAMENTO" ("TRATAMIENTO_MEDICAMENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "TRATAMIENTO_MEDICAMENTO" ADD CONSTRAINT "TRATAMIENTO_MEDICAMENTO_PK" PRIMARY KEY ("TRATAMIENTO_MEDICAMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TRATAMIENTO_MEDICAMENTO" MODIFY ("TRATAMIENTO_MEDICAMENTO_ID" NOT NULL ENABLE);
  
  ALTER TABLE "TRATAMIENTO_MEDICAMENTO" ADD CONSTRAINT "TRAT_MED_MED_FK1" FOREIGN KEY ("MEDICAMENTO_ID")
  REFERENCES "MEDICAMENTO" ("MEDICAMENTO_ID") ENABLE;
  ALTER TABLE "TRATAMIENTO_MEDICAMENTO" ADD CONSTRAINT "TRAT_MED_TRAT_FK1" FOREIGN KEY ("TRATAMIENTO_ID")
  REFERENCES "TRATAMIENTO" ("TRATAMIENTO_ID") ENABLE;
  

 CREATE SEQUENCE   "SECRETARIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "PACIENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "MEDICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "TURNO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "HISTORIA_CLINICA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "TIPO_ANTECEDENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "ANTECEDENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "CONSULTA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE   "DIAGNOSTICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "TRATAMIENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MEDICAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "TRATAMIENTO_MEDICAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/


		

