--------------------------------------------------------
-- Archivo creado  - viernes-enero-23-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANTECEDENTE_GENERAL
--------------------------------------------------------

  CREATE TABLE "ANTECEDENTE_GENERAL" 
   (	"ANTECEDENTE_GRAL_ID" NUMBER(8,0), 
	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"ANTECEDENTE_PESOALNACER" VARCHAR2(20), 
	"USUARIO_CREACION" VARCHAR2(20), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20), 
	"FECHA_MODIFICACION" DATE, 
	"ANTECEDENTE_TALLA" VARCHAR2(20), 
	"ANTECEDENTE_CCEFALIC" VARCHAR2(20), 
	"ANTECEDENTE_PARTO_NORMAL" VARCHAR2(20), 
	"ANTECEDENTE_PARTO_DISTOCICO" VARCHAR2(20), 
	"ANTECEDENTE_PARTO_CESARIA" VARCHAR2(20), 
	"ANTECEDENTE_COMPLICACIONES" VARCHAR2(20), 
	"ANTECEDENTE_SCOREDEAPGAR" VARCHAR2(20), 
	"ANTECEDENTE_SOCIO_ECONOMICO" VARCHAR2(20), 
	"ANTECEDENTE_DIABETES" VARCHAR2(20), 
	"ANTECEDENTE_ASMA" VARCHAR2(20), 
	"ANTECEDENTE_TBC" VARCHAR2(20), 
	"ANTECEDENTE_HIPERTENSION" VARCHAR2(20), 
	"ANTECEDENTE_PADRE" VARCHAR2(20), 
	"ANTECEDENTE_MADRE" VARCHAR2(20), 
	"ANTECEDENTE_HIJOS" VARCHAR2(20), 
	"ANTECEDENTE_HERMANOS" VARCHAR2(20), 
	"ANTECEDENTE_TABACO" VARCHAR2(20), 
	"ANTECEDENTE_ALCOHOL" VARCHAR2(20), 
	"ANTECEDENTE_ADICCION" VARCHAR2(20), 
	"ANTECEDENTE_OPERACIONANTERIOR" DATE, 
	"ANTECEDENTE_TIPOOPERACION" VARCHAR2(20), 
	"ANTECEDENTE_TRAUMATISMOS" DATE, 
	"ANTECEDENTE_LOCALIZACION" VARCHAR2(20), 
	"ANTECEDENTE_PESO" VARCHAR2(20), 
	"ANTECEDENTE_GENERAL_TALLA" VARCHAR2(20), 
	"ANTECEDENTE_TENSIONARTERIAL" VARCHAR2(20), 
	"ANTECEDENTE_PIELYFANERAS" VARCHAR2(20), 
	"ANTECEDENTE_VISION" VARCHAR2(20), 
	"ANTECEDENTE_AUDICION" VARCHAR2(20), 
	"ANTECEDENTE_ODONTOLOGIA" VARCHAR2(20), 
	"ANTECEDENTE_OBESIDAD" VARCHAR2(20), 
	"ANTECEDENTE_PESONORMAL" VARCHAR2(20), 
	"ANTECEDENTE_PESOBAJO" VARCHAR2(20), 
	"ANTECEDENTE_REACCION_ADVERSA" VARCHAR2(20)
   ) ;
--------------------------------------------------------
--  DDL for Table ANTECEDENTE_PER_PATOLOGICO
--------------------------------------------------------

  CREATE TABLE "ANTECEDENTE_PER_PATOLOGICO" 
   (	"ANTECEDENTE_PER_PAT_ID" NUMBER(8,0), 
	"ANTECEDENTE_PER_NOMBRE" VARCHAR2(20), 
	"ANTECEDENTE_PER_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(20), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20), 
	"FECHA_MODIFICACION" DATE, 
	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"DETALLE_PAT_ID" NUMBER(8,0)
   ) ;
--------------------------------------------------------
--  DDL for Table CONSULTA
--------------------------------------------------------

  CREATE TABLE "CONSULTA" 
   (	"CONSULTA_ID" NUMBER(8,0), 
	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"CONSULTA_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(20), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20), 
	"FECHA_MODIFICACION" DATE, 
	"CONSULTA_FECHA" DATE, 
	"CONSULTA_EXAMEN_FISICO" VARCHAR2(200), 
	"CONSULTA_EVOLUCION" VARCHAR2(200)
   ) ;
--------------------------------------------------------
--  DDL for Table DETALLE_PATOLOGIA
--------------------------------------------------------

  CREATE TABLE "DETALLE_PATOLOGIA" 
   (	"DETALLE_PAT_ID" NUMBER(8,0), 
	"PATOLOGIA_ID" NUMBER(8,0), 
	"DETALLE_PAT_NOMBRE" VARCHAR2(20), 
	"DETALLE_PAT_DESCRIPCION" VARCHAR2(200), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table DIAGNOSTICO
--------------------------------------------------------

  CREATE TABLE "DIAGNOSTICO" 
   (	"DIAGNOSTICO_ID" NUMBER(8,0), 
	"CONSULTA_ID" NUMBER(8,0), 
	"DIAGNOSTICO_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table HISTORIA_CLINICA
--------------------------------------------------------

  CREATE TABLE "HISTORIA_CLINICA" 
   (	"HISTORIA_CLINICA_ID" NUMBER(8,0), 
	"PACIENTE_ID" NUMBER(8,0), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_ID" NUMBER(8,0)
   ) ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "MEDICAMENTO" 
   (	"MEDICAMENTO_ID" NUMBER(8,0), 
	"MEDICAMENTO_NOMBRE" VARCHAR2(100), 
	"MEDICAMENTO_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------

  CREATE TABLE "PACIENTE" 
   (	"PACIENTE_ID" NUMBER(8,0), 
	"PACIENTE_NOMBRE" VARCHAR2(100), 
	"PACIENTE_APELLIDO" VARCHAR2(100), 
	"PACIENTE_DNI" VARCHAR2(50), 
	"PACIENTE_TELEFONO" VARCHAR2(50), 
	"PACIENTE_DOMICILIO_CALLE" VARCHAR2(50), 
	"PACIENTE_OBRA_SOCIAL" VARCHAR2(100), 
	"PACIENTE_EDAD" VARCHAR2(3), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE, 
	"PACIENTE_ESTADO_CIVIL" VARCHAR2(20), 
	"PACIENTE_FECHA_NACIMIENTO" DATE, 
	"PACIENTE_SEXO" VARCHAR2(20), 
	"PACIENTE_LUGAR_NACIMIENTO" VARCHAR2(50), 
	"PACIENTE_PROFESION" VARCHAR2(50), 
	"PACIENTE_NUMERO_AFILIADO" VARCHAR2(20), 
	"PACIENTE_DOMICILIO_NUMERO" VARCHAR2(50), 
	"PACIENTE_DOMICILIO_BARRIO" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table PATOLOGIA
--------------------------------------------------------

  CREATE TABLE "PATOLOGIA" 
   (	"PATOLOGIA_ID" NUMBER(8,0), 
	"PATOLOGIA_NOMBRE" VARCHAR2(50), 
	"PATOLOGIA_DESCRIPCION" VARCHAR2(200), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table PERMISO
--------------------------------------------------------

  CREATE TABLE "PERMISO" 
   (	"PERMISO_ID" NUMBER(8,0), 
	"PERMISO_NOMBRE" VARCHAR2(20), 
	"PERMISO_PERMISO" VARCHAR2(50), 
	"PERMISO_DESCRIPCION" VARCHAR2(250), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRATAMIENTO
--------------------------------------------------------

  CREATE TABLE "TRATAMIENTO" 
   (	"TRATAMIENTO_ID" NUMBER(8,0), 
	"DIAGNOSTICO_ID" NUMBER(8,0), 
	"TRATAMIENTO_DESCRIPCION" VARCHAR2(200), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TRATAMIENTO_MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "TRATAMIENTO_MEDICAMENTO" 
   (	"TRATAMIENTO_MEDICAMENTO_ID" NUMBER(8,0), 
	"MEDICAMENTO_ID" NUMBER(8,0), 
	"TRATAMIENTO_ID" NUMBER(8,0), 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TURNO
--------------------------------------------------------

  CREATE TABLE "TURNO" 
   (	"TURNO_ID" NUMBER(8,0), 
	"PACIENTE_ID" NUMBER(8,0), 
	"TURNO_FECHA" DATE, 
	"TURNO_HORA" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"FECHA_MODIFICACION" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "USUARIO" 
   (	"USUARIO_ID" NUMBER(8,0), 
	"PERMISO_ID" NUMBER(8,0), 
	"USUARIO_NOMBRE" VARCHAR2(100), 
	"USUARIO_APELLIDO" VARCHAR2(100), 
	"USUARIO_DNI" VARCHAR2(50), 
	"USUARIO_TELEFONO" VARCHAR2(50), 
	"USUARIO_DOMICILIO_BARRIO" VARCHAR2(50), 
	"USUARIO_USUARIO" VARCHAR2(50), 
	"USUARIO_CONTRASENIA" VARCHAR2(20), 
	"USUARIO_ROL" VARCHAR2(20), 
	"USUARIO_OBRA_SOCIAL" VARCHAR2(20), 
	"USUARIO_EDAD" VARCHAR2(3), 
	"USUARIO_MATRICULA" VARCHAR2(10), 
	"USUARIO_ESPECIALIDAD" VARCHAR2(20), 
	"USUARIO_HORA_ATENCION_MIN" DATE, 
	"USUARIO_HORA_ATENCION_MAX" DATE, 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"USUARIO_CREACION" VARCHAR2(100), 
	"USUARIO_MODIFICACION" VARCHAR2(100), 
	"USUARIO_DOMICILIO_CALLE" VARCHAR2(50), 
	"USUARIO_DOMICILIO_NUMERO" VARCHAR2(50)
   ) ;
