REM INSERTING into MEDICO
Insert into MEDICO (MEDICO_ID,MEDICO_NOMBRE,MEDICO_APELLIDO,MEDICO_DNI,MEDICO_TELEFONO,MEDICO_DIRECCION,MEDICO_USUARIO,MEDICO_CONTRASENIA,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) 
values ('1',
'maya',
 'alcon',
 'dni2',
 'tel2',
 'dir2',
 'user2',
 'pass2',
 null,null,null,null);
 COMMIT;